<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Challenge-2" data-toc-modified-id="Challenge-2-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Challenge 2</a></span><ul class="toc-item"><li><span><a href="#Problem-Solving-Iteration-1" data-toc-modified-id="Problem-Solving-Iteration-1-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Problem Solving Iteration 1</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#The-Total-field-is-computed-based-on-HP,-Attack,-Defense,-Sp.-Atk,-Sp.-Def,-and-Speed." data-toc-modified-id="The-Total-field-is-computed-based-on-HP,-Attack,-Defense,-Sp.-Atk,-Sp.-Def,-and-Speed.-1.1.0.1"><span class="toc-item-num">1.1.0.1&nbsp;&nbsp;</span>The <code>Total</code> field is computed based on <code>HP</code>, <code>Attack</code>, <code>Defense</code>, <code>Sp. Atk</code>, <code>Sp. Def</code>, and <code>Speed</code>.</a></span></li></ul></li></ul></li><li><span><a href="#Problem-Solving-Iteration-2" data-toc-modified-id="Problem-Solving-Iteration-2-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Problem Solving Iteration 2</a></span><ul class="toc-item"><li><span><a href="#Which-pokemon-type-is-most-likely-to-have-the-highest-Total-value?" data-toc-modified-id="Which-pokemon-type-is-most-likely-to-have-the-highest-Total-value?-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Which pokemon type is most likely to have the highest <code>Total</code> value?</a></span><ul class="toc-item"><li><span><a href="#Type-1-and-Type-2-string-variables-need-to-be-converted-to-numerical-variables-in-order-to-identify-the-relationship-between-Total-and-the-pokemon-type." data-toc-modified-id="Type-1-and-Type-2-string-variables-need-to-be-converted-to-numerical-variables-in-order-to-identify-the-relationship-between-Total-and-the-pokemon-type.-1.2.1.1"><span class="toc-item-num">1.2.1.1&nbsp;&nbsp;</span><code>Type 1</code> and <code>Type 2</code> string variables need to be converted to numerical variables in order to identify the relationship between <code>Total</code> and the pokemon type.</a></span></li><li><span><a href="#How-to-convert-two-string-variables-to-numerical?" data-toc-modified-id="How-to-convert-two-string-variables-to-numerical?-1.2.1.2"><span class="toc-item-num">1.2.1.2&nbsp;&nbsp;</span>How to convert two string variables to numerical?</a></span></li><li><span><a href="#In-the-next-cell,-use-One-Hot-Encoding-to-encode-Type-1-and-Type-2.-Use-the-pokemon-type-values-as-the-names-of-the-numerical-fields-you-create." data-toc-modified-id="In-the-next-cell,-use-One-Hot-Encoding-to-encode-Type-1-and-Type-2.-Use-the-pokemon-type-values-as-the-names-of-the-numerical-fields-you-create.-1.2.1.3"><span class="toc-item-num">1.2.1.3&nbsp;&nbsp;</span>In the next cell, use One Hot Encoding to encode <code>Type 1</code> and <code>Type 2</code>. Use the pokemon type values as the names of the numerical fields you create.</a></span></li></ul></li></ul></li><li><span><a href="#Problem-Solving-Iteration-3" data-toc-modified-id="Problem-Solving-Iteration-3-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Problem Solving Iteration 3</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#There-are-relationships-between-Total-and-the-encoded-pokemon-type-variables-and-we-need-to-identify-the-correlations." data-toc-modified-id="There-are-relationships-between-Total-and-the-encoded-pokemon-type-variables-and-we-need-to-identify-the-correlations.-1.3.0.1"><span class="toc-item-num">1.3.0.1&nbsp;&nbsp;</span>There are relationships between <code>Total</code> and the encoded pokemon type variables and we need to identify the correlations.</a></span></li><li><span><a href="#How-to-identify-the-relationship-between-Total-and-the-encoded-pokemon-type-fields?" data-toc-modified-id="How-to-identify-the-relationship-between-Total-and-the-encoded-pokemon-type-fields?-1.3.0.2"><span class="toc-item-num">1.3.0.2&nbsp;&nbsp;</span>How to identify the relationship between <code>Total</code> and the encoded pokemon type fields?</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Bonus-Question" data-toc-modified-id="Bonus-Question-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Bonus Question</a></span></li></ul></div>

# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [1]:
# Import libraries
import numpy as np
import pandas as pd

In [3]:
# Importing the dataset from Ironhack's database
df=pd.read_csv('Pokemon.csv')
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [54]:
# your code here
## use where condition to check that sume of other columns = total

df['total_gm']= df.iloc[:,5:11].sum(axis = 1)
df
set(df['Total']==df['total_gm']) # returns 800 rows as in original df, so total is indeed sum of the different columns

{True}

Comment: Yeah, Total is just a sum of all those columns

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

In [50]:
# your code here
Hot_types=pd.get_dummies(df['Type 1']) + pd.get_dummies(df['Type 2'])

yunke's coded to make hot enocde


pd.options.display.max_columns = 999

for i in types:
    df[i]=np.where((df['Type 1'].astype(str) ==i) | (df['Type 2'].astype(str) == i),
                  1,
                  0)
df

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [56]:
df_total=df[['Total']]
df_total

     Total
0      318
1      405
2      525
3      625
4      309
..     ...
795    600
796    700
797    600
798    680
799    600

[800 rows x 1 columns]

In [63]:
# your code here
corr_df=pd.merge( df_total, Hot_types, left_index=True, right_index=True).corr()
corr_df
#df_corr.head(5)
#corr_df=corr_df.corr()

,Total,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
Total,1.000000,-0.145781,0.056154,0.229705,0.020971,-0.036698,0.077786,0.078726,0.059383,0.003641,-0.052592,0.015060,0.060248,-0.105331,-0.090441,0.124688,0.032731,0.109703,-0.021665
Bug,-0.145781,1.000000,-0.082062,-0.081200,-0.045111,-0.072148,-0.048645,-0.060536,0.064571,-0.058915,-0.034430,-0.063544,-0.070229,-0.120219,0.121210,-0.111968,-0.003706,0.047178,-0.123983
Dark,0.056154,-0.082062,1.000000,-0.003963,-0.067375,-0.059864,-0.007791,-0.020368,-0.022164,0.001484,-0.048339,-0.023480,-0.010163,-0.099751,-0.018227,-0.044327,-0.033493,-0.023978,-0.028548
Dragon,0.229705,-0.081200,-0.003963,1.000000,-0.024000,-0.035541,-0.068775,-0.038069,0.026237,-0.019410,-0.078818,0.052430,0.015173,-0.098702,-0.055525,-0.026557,-0.032360,-0.044417,-0.083285
Electric,0.020971,-0.045111,-0.067375,-0.024000,1.000000,-0.035541,-0.068775,-0.057104,-0.020407,-0.041592,-0.078818,-0.059420,-0.033382,-0.067737,-0.074838,-0.091928,-0.072188,-0.001346,-0.069109
Fairy,-0.036698,-0.072148,-0.059864,-0.035541,-0.035541,1.000000,-0.061108,-0.067651,-0.052669,-0.056665,-0.048756,-0.069360,-0.051232,-0.001720,-0.066495,0.027227,0.002212,0.013155,-0.067703
Fighting,0.077786,-0.048645,-0.007791,-0.068775,-0.068775,-0.061108,1.000000,0.051130,-0.086119,-0.065792,-0.051171,-0.080531,-0.059483,-0.071687,-0.039613,0.000596,-0.055090,-0.005161,-0.073778
Fire,0.078726,-0.060536,-0.020368,-0.038069,-0.057104,-0.067651,0.051130,1.000000,-0.028855,-0.013459,-0.108248,-0.022621,-0.065851,-0.085097,-0.085471,-0.061243,-0.064677,-0.056108,-0.114850
Flying,0.059383,0.064571,-0.022164,0.026237,-0.020407,-0.052669,-0.086119,-0.028855,1.000000,-0.061555,-0.081366,-0.060578,-0.049498,0.125506,-0.067950,-0.063872,-0.048221,-0.081400,-0.092030
Ghost,0.003641,-0.058915,0.001484,-0.019410,-0.041592,-0.056665,-0.065792,-0.013459,-0.061555,1.000000,0.075316,-0.035908,-0.029914,-0.094420,0.008736,-0.070947,-0.069057,0.026479,-0.077314
Grass,-0.052592,-0.034430,-0.048339,-0.078818,-0.078818,-0.048756,-0.051171,-0.108248,-0.081366,0.075316,1.000000,-0.097033,-0.027476,-0.117156,0.110372,-0.094009,-0.072829,-0.061537,-0.126894
Ground,0.015060,-0.063544,-0.023480,0.052430,-0.059420,-0.069360,-0.080531,-0.022621,-0.060578,-0.035908,-0.097033,1.000000,-0.003872,-0.102044,-0.053878,-0.079079,0.072085,-0.020771,-0.006844
Ice,0.060248,-0.070229,-0.010163,0.015173,-0.033382,-0.051232,-0.059483,-0.065851,-0.049498,-0.029914,-0.027476,-0.003872,1.000000,-0.085366,-0.064726,-0.042311,-0.017110,-0.057042,0.000242
Normal,-0.105331,-0.120219,-0.099751,-0.098702,-0.067737,-0.001720,-0.071687,-0.085097,0.125506,-0.094420,-0.117156,-0.102044,-0.085366,1.000000,-0.110800,-0.112381,-0.106877,-0.097645,-0.154994
Poison,-0.090441,0.121210,-0.018227,-0.055525,-0.074838,-0.066495,-0.039613,-0.085471,-0.067950,0.008736,0.110372,-0.053878,-0.064726,-0.110800,1.000000,-0.103195,-0.081036,-0.074036,-0.073986
Psychic,0.124688,-0.111968,-0.044327,-0.026557,-0.091928,0.027227,0.000596,-0.061243,-0.063872,-0.070947,-0.094009,-0.079079,-0.042311,-0.112381,-0.103195,1.000000,-0.069031,0.024540,-0.099639
Rock,0.032731,-0.003706,-0.033493,-0.032360,-0.072188,0.002212,-0.055090,-0.064677,-0.048221,-0.069057,-0.072829,0.072085,-0.017110,-0.106877,-0.081036,-0.069031,1.000000,0.049202,0.011447
Steel,0.109703,0.047178,-0.023978,-0.044417,-0.001346,0.013155,-0.005161,-0.056108,-0.081400,0.026479,-0.061537,-0.020771,-0.057042,-0.097645,-0.074036,0.024540,0.049202,1.000000,-0.096131
Water,-0.021665,-0.123983,-0.028548,-0.083285,-0.069109,-0.067703,-0.073778,-0.114850,-0.092030,-0.077314,-0.126894,-0.006844,0.000242,-0.154994,-0.073986,-0.099639,0.011447,-0.096131,1.000000

In [64]:
corr_df[['Total']].sort_values(by='Total', ascending=False).head(10)
## Dragon best type to pick

             Total
Total     1.000000
Dragon    0.229705
Psychic   0.124688
Steel     0.109703
Fire      0.078726
Fighting  0.077786
Ice       0.060248
Flying    0.059383
Dark      0.056154
Rock      0.032731

# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

In [ ]:
# your code here

# from above table pick Dragon and Pyschic types

#use get_dummies on combo_type columns
#do correlation
# and use nlargest to get the best combo